(function(){
  const TEST_ID='python-basics-sample-01';
  const state={sourceTest:null,test:null,mode:'total-timed',feedback:'on-completion',sound:true,current:0,answers:[],checked:[],started:0,totalEnd:0,questionEnd:0,timer:null,lastWrong:[]};
  const app=document.getElementById('app');
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const time=s=>`${String(Math.floor(Math.max(0,s)/60)).padStart(2,'0')}:${String(Math.max(0,s)%60).padStart(2,'0')}`;
  function toast(message){const el=document.getElementById('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
  function tone(f=650){if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C,o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.value=.035;o.connect(g);g.connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.1);o.stop(c.currentTime+.1)}catch(_){}}
  async function init(){try{const [config,data]=await Promise.all([Api.request('site-main.json'),Api.request('tests.json')]);state.sourceTest=data.tests.find(t=>t.id===TEST_ID);if(!state.sourceTest)throw Error('Python test was not found in tests.json');state.test=clone(state.sourceTest);document.title=`${state.test.title} | ${config.site.name}`;renderSetup()}catch(error){app.innerHTML=`<section class="panel"><h1>Test could not be loaded</h1><p>${esc(error.message)}</p><button class="primary" onclick="location.reload()">Retry</button></section>`}}
  function clone(value){return JSON.parse(JSON.stringify(value))}
  function shuffle(items){const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result}
  function shuffleQuestion(question){const pairs=question.options.map((option,index)=>({option,index}));const mixed=shuffle(pairs);return{...clone(question),options:mixed.map(item=>item.option),correctOption:mixed.findIndex(item=>item.index===question.correctOption)}}
  function makeAttempt(questions,label=''){const source=state.sourceTest;const mixedQuestions=shuffle(questions.map(shuffleQuestion));const marks=mixedQuestions.reduce((sum,q)=>sum+q.marks,0);const secondsPerQuestion=source.timing.totalSeconds/source.questions.length;return{...clone(source),title:label?`${source.title} — ${label}`:source.title,questions:mixedQuestions,totalMarks:marks,timing:{...source.timing,totalSeconds:Math.max(60,Math.round(secondsPerQuestion*mixedQuestions.length))}}}
  function renderSetup(){const t=state.sourceTest;app.innerHTML=`<section class="setup"><article class="intro"><span class="eyebrow">JSON-POWERED CLIENT REVIEW</span><h1>${t.title}</h1><p>${t.description}</p><div class="facts"><div><strong>${t.questions.length}</strong><span>Questions</span></div><div><strong>${t.totalMarks}</strong><span>Total marks</span></div><div><strong>${Math.round(t.timing.totalSeconds/60)} min</strong><span>Default time</span></div></div></article><aside class="panel"><h2>Choose features to test</h2><fieldset class="option-group"><legend>Timing</legend>${option('mode','total-timed','Total-test timer','One clock for the complete test',true)}${option('mode','question-timed','Per-question timer',`${t.timing.questionSeconds} seconds per question`)}${option('mode','untimed','Untimed','Show elapsed time only')}</fieldset><fieldset class="option-group"><legend>Answer checking</legend>${option('feedback','on-completion','After submission','Keep answers hidden during the test',true)}${option('feedback','per-question','After each question','Show correctness and explanation immediately')}</fieldset><label class="toggle"><span><strong>Sounds</strong><small>Timer and answer feedback</small></span><input id="sound" type="checkbox" checked></label><button class="primary full" id="start">Start Python test →</button></aside></section>`;document.getElementById('start').onclick=start}
  function option(name,value,title,description,checked=false){return `<label class="feature-option"><input type="radio" name="${name}" value="${value}" ${checked?'checked':''}><span><strong>${title}</strong><small>${description}</small></span></label>`}
  function start(){state.mode=document.querySelector('[name=mode]:checked').value;state.feedback=document.querySelector('[name=feedback]:checked').value;state.sound=document.getElementById('sound').checked;beginAttempt(clone(state.sourceTest))}
  function beginAttempt(test){clearInterval(state.timer);state.test=test;state.current=0;state.answers=Array(test.questions.length).fill(null);state.checked=Array(test.questions.length).fill(false);state.started=Date.now();state.totalEnd=Date.now()+test.timing.totalSeconds*1000;open(0);tone(760)}
  function open(index){state.current=index;if(state.mode==='question-timed')state.questionEnd=Date.now()+state.test.timing.questionSeconds*1000;renderQuestion();runClock()}
  function renderQuestion(){const t=state.test,q=t.questions[state.current],selected=state.answers[state.current],checked=state.checked[state.current];app.innerHTML=`<section><header class="test-header"><div><h1>${t.title}</h1><p>Question ${state.current+1} of ${t.questions.length}</p></div><span class="clock" id="clock"></span></header><div class="progress"><i style="width:${(state.current+1)/t.questions.length*100}%"></i></div><div class="test-layout"><article class="question-card"><div class="question-meta"><span>${q.topic}</span><span>${q.marks} mark${q.marks>1?'s':''}</span></div><h2>${q.question}</h2>${q.code?`<pre><code>${esc(q.code)}</code></pre>`:''}<div class="answers">${q.options.map((answer,i)=>`<label class="answer ${answerClass(i,q,selected,checked)}"><input type="radio" name="answer" value="${i}" ${selected===i?'checked':''} ${checked?'disabled':''}><b>${String.fromCharCode(65+i)}</b><span>${answer}</span></label>`).join('')}</div>${checked?`<div class="feedback ${selected===q.correctOption?'good':'bad'}"><strong>${selected===q.correctOption?'Correct':'Incorrect'}</strong><p>${q.explanation}</p></div>`:''}<div class="actions"><button class="secondary" id="clear" ${checked?'disabled':''}>Clear</button><button class="primary" id="next">${state.feedback==='per-question'&&!checked?'Check answer':state.current===t.questions.length-1?'Finish test':'Save & next'} →</button></div></article><aside class="palette"><h3>Questions</h3><div class="numbers">${t.questions.map((_,i)=>`<button data-q="${i}" class="${state.answers[i]!==null?'answered ':''}${i===state.current?'current':''}">${i+1}</button>`).join('')}</div><button class="danger" id="finish">Finish test</button></aside></div></section>`;document.querySelectorAll('[name=answer]').forEach(input=>input.onchange=e=>{state.answers[state.current]=Number(e.target.value);tone(520);renderQuestion();runClock()});document.querySelectorAll('[data-q]').forEach(button=>button.onclick=()=>open(Number(button.dataset.q)));document.getElementById('clear').onclick=()=>{state.answers[state.current]=null;renderQuestion();runClock()};document.getElementById('next').onclick=next;document.getElementById('finish').onclick=()=>confirm('Finish and calculate the result?')&&finish();updateClock()}
  function answerClass(i,q,selected,checked){if(!checked)return selected===i?'selected':'';if(i===q.correctOption)return'correct';return selected===i?'wrong':''}
  function next(){const answer=state.answers[state.current];if(state.feedback==='per-question'&&!state.checked[state.current]){if(answer===null)return toast('Select an answer first.');state.checked[state.current]=true;tone(answer===state.test.questions[state.current].correctOption?900:300);renderQuestion();runClock();return}if(state.current===state.test.questions.length-1)finish();else open(state.current+1)}
  function runClock(){clearInterval(state.timer);updateClock();state.timer=setInterval(updateClock,500)}
  function updateClock(){const el=document.getElementById('clock');if(!el)return;if(state.mode==='untimed'){el.textContent=`Elapsed ${time(Math.floor((Date.now()-state.started)/1000))}`;return}const end=state.mode==='total-timed'?state.totalEnd:state.questionEnd,seconds=Math.max(0,Math.ceil((end-Date.now())/1000));el.textContent=`${state.mode==='total-timed'?'Total':'Question'} ${time(seconds)}`;el.classList.toggle('urgent',seconds<=state.test.timing.warningSeconds);if(seconds===0){clearInterval(state.timer);tone(250);if(state.mode==='total-timed'||state.current===state.test.questions.length-1)finish();else open(state.current+1)}}
  function finish(){
    clearInterval(state.timer);
    const t=state.test;
    const correct=t.questions.filter((q,i)=>state.answers[i]===q.correctOption).length;
    const attempted=state.answers.filter(v=>v!==null).length;
    const incorrect=attempted-correct;
    const score=t.questions.reduce((sum,q,i)=>sum+(state.answers[i]===q.correctOption?q.marks:0),0);
    const percent=Math.round(score/t.totalMarks*100);
    const elapsed=Math.floor((Date.now()-state.started)/1000);
    state.lastWrong=t.questions.filter((q,i)=>state.answers[i]!==null&&state.answers[i]!==q.correctOption).map(clone);
    app.innerHTML=`<section><article class="result-hero"><span class="eyebrow">FEATURE TEST COMPLETE</span><div class="score">${percent}%</div><h1>${percent>=t.passPercent?'Good foundation':'More practice will help'}</h1><p>Retakes shuffle both the question order and every question's answer options.</p><div class="result-actions"><button class="primary" id="retakeAll">Retake all · shuffled</button><button class="secondary" id="retestWrong" ${state.lastWrong.length?'':'disabled'}>Retest wrong answers · shuffled</button><button class="secondary" id="again">Change settings</button></div>${state.lastWrong.length?'':`<small class="perfect-note">No wrong answers—wrong-answer retest is not needed.</small>`}</article><div class="result-grid"><div><strong>${correct}</strong><span>Correct</span></div><div><strong>${incorrect}</strong><span>Incorrect</span></div><div><strong>${t.questions.length-attempted}</strong><span>Unanswered</span></div><div><strong>${time(elapsed)}</strong><span>Time</span></div></div><div class="review">${t.questions.map((q,i)=>`<article class="review-card ${state.answers[i]===q.correctOption?'good':'bad'}"><span class="eyebrow">QUESTION ${i+1} · ${q.topic}</span><h3>${q.question}</h3><p><b>Your answer:</b> ${state.answers[i]===null?'Not answered':q.options[state.answers[i]]}</p><p><b>Correct answer:</b> ${q.options[q.correctOption]}</p><p>${q.explanation}</p></article>`).join('')}</div></section>`;
    document.getElementById('retakeAll').onclick=()=>beginAttempt(makeAttempt(state.sourceTest.questions,'Shuffled Retake'));
    document.getElementById('retestWrong').onclick=()=>state.lastWrong.length&&beginAttempt(makeAttempt(state.lastWrong,'Wrong Answers Retest'));
    document.getElementById('again').onclick=renderSetup;
    window.scrollTo(0,0);
  }
  init();
}());
